project: decision_for_screening

# -- Initiation characteristics of the model
model_type: "linear"
value_function: "rel_point_cond_mut_info"
elicit: False  # It can be True, False 
noise: True # (for sensitivity analysis purposes)
noise_std: 0.3
lambda_list_from_config: True
lambda_list: [4.011942483017116, 4.168480067521723, 6.801984517973132, 7.0]

patient_chars: {"Age": "age_4_adult", 
                        "Sex": "M",
                        "SD": "SD_2_normal",
                        "PA": "PA_2",
                        "Smoking": "sm_1_not_smoker",
                        "BMI": "bmi_2_normal",
                        "Alcohol": "low"
                        }

# -- Flag for calculating values
calculate_info_values: True


# -- Flag for assigning a new test
new_test: True 

# --------- If new_test = True, the following parameters must be defined
# TODO test names should be able to be changed in the API by the user. (Not only New_test_A and New_test_B)
new_tests:
  New_Test_A:
    cost: 3
    sensitivity: 0.85
    specificity: 0.94
    comfort_level: 3
  New_Test_B:
    cost: 8
    sensitivity: 0.9
    specificity: 0.96
    comfort_level: 3
# -------------------------------------------------------------------------


# -- For the elicitation step
point_cond_mut_info:
  PE_cost: 200     # Probability equivalent cost
  PE_info: 0.01     # Probability equivalent info
  PE_prob: 0.7     # Probability of equivalence

rel_point_cond_mut_info:
  PE_cost: 50     # Probability equivalent cost
  PE_info: 4.1     # Probability equivalent info
  PE_prob: 0.7    # Probability of equivalence


full_example:
  PE_cost_array: [5, 10, 50] 
  PE_info_array:  [4.2, 4.1, 4]
# -------------------------------------------------------------------------

# -- Lower bound of estimation of performance metrics

sens_analysis_metrics_lower: 
  screening: [
    # Specificity
    1, 0, 0,          # No screening
    0, 0.843, 0.157,  # gFOBT
    0, 0.92, 0.08,    # FIT
    0, 0.606, 0.394,  # Blood-based
    0, 0.859, 0.141,  # Stool DNA
    0, 0.89, 0.11,    # CTC
    0, 0.89, 0.11,    # Colon capsule

    # Sensitivity
    1, 0, 0,          # No screening
    0, 0.631, 0.369,  # gFOBT
    0, 0.35, 0.65,    # FIT
    0, 0.212, 0.788,  # Blood-based
    0, 0.170, 0.830,  # Stool DNA
    0, 0.05, 0.95,    # CTC
    0, 0.17, 0.83,    # Colon capsule
  ]

  colonoscopy: [
  
    # Specificity
    1, 0, 0,          # No colonoscopy
    0, 0.99, 0.01,    # Colonoscopy

    # Sensitivity
    1, 0, 0,          # No colonoscopy
    0, 0.03, 0.97,    # Colonoscopy
  ]



sens_analysis_metrics_upper: {
  "screening": [

    # Specificity
    1, 0, 0,          # No screening
    0, 0.961, 0.039,  # gFOBT
    0, 0.95, 0.05,    # FIT
    0, 0.786, 0.214,  # Blood-based
    0, 0.872, 0.128,  # Stool DNA
    0, 0.89, 0.11,    # CTC
    0, 0.95, 0.05,    # Colon capsule

    # Sensitivity
    1, 0, 0,          # No screening  
    0, 0.418, 0.582,  # gFOBT
    0, 0.11,  0.89,   # FIT
    0, 0.068, 0.932,  # Blood-based
    0, 0.025, 0.975,  # Stool DNA
    0, 0.05,  0.95,   # CTC
    0, 0.09,  0.91,   # Colon capsule

  ],

  "colonoscopy": [

    # Specificity
    1, 0, 0,          # No colonoscopy
    0, 0.99, 0.01,    # Colonoscopy

    # Sensitivity
    1, 0, 0,          # No colonoscopy
    0, 0.03,  0.97,   # Colonoscopy
  ],

}

# -------------------------------------------------------------------------



# -- Assignning colors to the different screening strategies
colors:
  No_screening: '#1f77b4'
  gFOBT: '#ff7f0e'
  FIT: '#2ca02c'
  Blood_based: '#d62728'
  Stool_DNA: '#9467bd'
  CTC: '#8c564b'
  Colon_capsule: '#e377c2'
  Colonoscopy: '#bcbd22'
  New_test: '#17becf'        # Possible name for new test, change if necessary.
  H(CRC): '#7f7f7f' 




# -- Use case

single_run: True
num_runs: 50
max_workers: 4
  
all_variables: True
from_elicitation: False

operational_limit : {
        "No_scr_no_col": "inf",
        "No_scr_col": 3000,
        "gFOBT": 30000,
        "FIT": 42000,
        "Blood_based": 7000,
        "Stool_DNA": 6000,
        "CTC": 2000,
        "Colon_capsule": 2000,
    }


operational_limit_comp : {
        "No_scr_no_col": "inf",
        "No_scr_col": 0,
        "gFOBT": 0,
        "FIT": 49074,
        "Blood_based": 0,
        "Stool_DNA": 0,
        "CTC": 0,
        "Colon_capsule": 0,
        }


operational_limit_new_test : {
        "No_scr_no_col": "inf",
        "No_scr_col": 3000,
        "gFOBT": 30000,
        "FIT": 42000,
        "Blood_based": 7000,
        "Stool_DNA": 5000,
        "CTC": 2000,
        "Colon_capsule": 2000,
        "New_test": 50000,
        }